catalog
catalogKeyClassesAndExample
	"Returns a paragraph or more describing the key classes of your project. You can use Pillar/Pier syntax to layout out the text i.e., ==Code== and - for bullet."
	^ 'The core classes are ZTimestamp to represent a point in time, ZTimestampFormat to format and parse chronology objects by example, ZTimezone to compute local time offsets and ZTimestampSNTPClient to check the clock against an network time server.'